import { AuthProtector } from "@/components/auth-protector";
import RedirectToast from "@/components/redirect-toast";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { UserRoleStoreProvider } from "@/providers/user-role-store-provider";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-y-hidden`}>
        <ThemeProvider>
          <UserRoleStoreProvider>
            <SessionProvider>
              {children}
              {/* <AuthProtector>{children}</AuthProtector> */}
            </SessionProvider>
          </UserRoleStoreProvider>
          <Toaster expand />
          <RedirectToast />
        </ThemeProvider>
      </body>
    </html>
  );
}
